import { DEFAULT } from '../constants';
import { CaseElements } from './types';

const DEFAULT_EXPECTED_VALUE = DEFAULT.return;

export const validCases: CaseElements = [
  { id: 1, input: { h: 0, s: 0, v: 0 }, expected: [0, 0, 0] },
  { id: 2, input: { h: 1, s: 2, v: 3 }, expected: [1, 2, 3] },
  { id: 3, input: { h: 100, s: 100, v: 100 }, expected: [100, 100, 100] },
  { id: 4, input: { h: 360, s: 100, v: 100 }, expected: [360, 100, 100] },
  { id: 5, input: { h: 360, s: 360, v: 360 }, expected: [360, 100, 100] },
  { id: 6, input: { h: 1000, s: 1000, v: 1000 }, expected: [360, 100, 100] },
  { id: 7, input: { h: -10, s: -100, v: -1 }, expected: [0, 0, 0] },
  { id: 8, input: { h: 50, s: -3, v: 4 }, expected: [50, 0, 4] },
  { id: 9, input: { h: -22, s: 99, v: '39' }, expected: [0, 99, 39] },
  { id: 10, input: { h: '43', s: '64.9', v: 5.3 }, expected: [43, 64, 5] },
  { id: 11, input: { h: '+6', s: '-5', v: '-4' }, expected: [6, 0, 0] },
  { id: 12, input: { h: 220.999, s: 101.4, v: 4.0001 }, expected: [220, 100, 4] },
  { id: 13, input: { h: 'two', s: 'some', v: true }, expected: [0, 0, 1] },
  { id: 14, input: { h: true, s: true, v: false }, expected: [1, 1, 0] },
  { id: 15, input: { h: true, s: true, v: true }, expected: [1, 1, 1] },
  { id: 16, input: { h: () => 2, s: () => 55, v: () => 1005 }, expected: [2, 55, 100] },
  { id: 17, input: { h: () => '+6', s: () => '-45', v: () => false }, expected: [6, 0, 0] },
  { id: 18, input: { h: () => '--5', s: () => '++2', v: () => 0 }, expected: [0, 0, 0] },
  { id: 19, input: { h: () => 'some', s: () => 'five', v: () => true }, expected: [0, 0, 1] },
  { id: 20, input: { h: () => 54, s: () => 54.3, v: () => 54.9 }, expected: [54, 54, 54] },
  { id: 1, input: () => ({ h: 0, s: 0, v: 0 }), expected: [0, 0, 0] },
  { id: 2, input: () => ({ h: 1, s: 2, v: 3 }), expected: [1, 2, 3] },
  { id: 3, input: () => ({ h: 100, s: 100, v: 100 }), expected: [100, 100, 100] },
  { id: 4, input: () => ({ h: 360, s: 100, v: 100 }), expected: [360, 100, 100] },
  { id: 5, input: () => ({ h: 360, s: 360, v: 360 }), expected: [360, 100, 100] },
  { id: 6, input: () => ({ h: 1000, s: 1000, v: 1000 }), expected: [360, 100, 100] },
  { id: 7, input: () => ({ h: -10, s: -100, v: -1 }), expected: [0, 0, 0] },
  { id: 8, input: () => ({ h: 50, s: -3, v: 4 }), expected: [50, 0, 4] },
  { id: 9, input: () => ({ h: -22, s: 99, v: '39' }), expected: [0, 99, 39] },
  { id: 10, input: () => ({ h: '43', s: '64.99', v: 5.3 }), expected: [43, 64, 5] },
  { id: 11, input: () => ({ h: '+6', s: '-5', v: '-4' }), expected: [6, 0, 0] },
  { id: 12, input: () => ({ h: 220.999, s: 101.4, v: 4.0001 }), expected: [220, 100, 4] },
  { id: 13, input: () => ({ h: 'two', s: 'some', v: true }), expected: [0, 0, 1] },
  { id: 14, input: () => ({ h: true, s: true, v: false }), expected: [1, 1, 0] },
  { id: 15, input: () => ({ h: true, s: true, v: true }), expected: [1, 1, 1] },
  { id: 16, input: () => ({ h: () => 2, s: () => 55, v: () => 1005 }), expected: [2, 55, 100] },
  { id: 17, input: () => ({ h: () => '+6', s: () => '-45', v: () => false }), expected: [6, 0, 0] },
  { id: 18, input: () => ({ h: () => '--5', s: () => '++2', v: () => 0 }), expected: [0, 0, 0] },
  {
    id: 19,
    input: () => ({ h: () => 'some', s: () => 'five', v: () => true }),
    expected: [0, 0, 1],
  },
  { id: 20, input: () => ({ h: () => 54, s: () => 54.3, v: () => 54.9 }), expected: [54, 54, 54] },
];

export const invalidCases: CaseElements = [
  { id: 1, input: 0, expected: DEFAULT_EXPECTED_VALUE },
  { id: 2, input: 44, expected: DEFAULT_EXPECTED_VALUE },
  { id: 3, input: '+89', expected: DEFAULT_EXPECTED_VALUE },
  { id: 4, input: 500, expected: DEFAULT_EXPECTED_VALUE },
  { id: 5, input: -1000, expected: DEFAULT_EXPECTED_VALUE },
  { id: 6, input: '-34', expected: DEFAULT_EXPECTED_VALUE },
  { id: 7, input: false, expected: DEFAULT_EXPECTED_VALUE },
  { id: 8, input: true, expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 9,
    input: { name: 'John' },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 10, input: 'John', expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 11,
    input: 3.3333,
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 12, input: () => 3, expected: DEFAULT_EXPECTED_VALUE },
  { id: 13, input: new Set(), expected: DEFAULT_EXPECTED_VALUE },
  { id: 14, input: new Map(), expected: DEFAULT_EXPECTED_VALUE },
  { id: 15, input: Symbol(4), expected: DEFAULT_EXPECTED_VALUE },
  { id: 16, input: new Error(), expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 17,
    input: { r: 'John', g: '++5', b: '--10' },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 18,
    input: { r: () => 'John', g: () => ({}), b: () => {} },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 19,
    input: { r: { name: 'John' }, g: {}, b: [] },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 20,
    input: { r: [34, 24, 'Aug', () => {}], g: [[], [2]], b: [[]] },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 21,
    input: { r: undefined, g: null, b: NaN },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 22,
    input: { r: () => undefined, g: () => null, b: () => NaN },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 23,
    input: { r: new Map(), g: new Set(), b: new Error() },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 24,
    input: { r: 'one', g: 'два', b: 'tri' },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 25, input: () => 0, expected: DEFAULT_EXPECTED_VALUE },
  { id: 26, input: () => 44, expected: DEFAULT_EXPECTED_VALUE },
  { id: 27, input: () => '+89', expected: DEFAULT_EXPECTED_VALUE },
  { id: 28, input: () => 500, expected: DEFAULT_EXPECTED_VALUE },
  { id: 29, input: () => -1000, expected: DEFAULT_EXPECTED_VALUE },
  { id: 30, input: () => '-34', expected: DEFAULT_EXPECTED_VALUE },
  { id: 31, input: () => false, expected: DEFAULT_EXPECTED_VALUE },
  { id: 32, input: () => true, expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 33,
    input: () => ({ name: 'John' }),
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 34, input: () => 'John', expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 35,
    input: null,
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 36,
    input: () => null,
    expected: DEFAULT_EXPECTED_VALUE,
  },
];
