export enum FunctionNames {
  cmykArrayToObj = 'cmykArrayToObj',
  cmykObjToArray = 'cmykObjToArray',
  cmykObjToRgbObj = 'cmykObjToRgbObj',
  cmykObjToString = 'cmykObjToString',
  cmykStringToObj = 'cmykStringToObj',
  hexStringToRgbObj = 'hexStringToRgbObj',
  hsvArrayToObj = 'hsvArrayToObj',
  hsvObjToArray = 'hsvObjToArray',
  hsvObjToRgbObj = 'hsvObjToRgbObj',
  hsvObjToString = 'hsvObjToString',
  hsvStringToObj = 'hsvStringToObj',
  rgbArrayToObj = 'rgbArrayToObj',
  rgbObjToArray = 'rgbObjToArray',
  rgbObjToCmykObj = 'rgbObjToCmykObj',
  rgbObjToHexString = 'rgbObjToHexString',
  rgbObjToHsvObj = 'rgbObjToHsvObj',
  rgbObjToString = 'rgbObjToString',
  rgbStringToObj = 'rgbStringToObj',
}
