"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT = exports.DEFAULT_HSV_VALUE_COMPONENT = exports.MAX_HSV_VALUE_COMPONENT = exports.MIN_HSV_VALUE_COMPONENT = exports.DEFAULT_HSV_SATURATION_COMPONENT = exports.MAX_HSV_SATURATION_COMPONENT = exports.MIN_HSV_SATURATION_COMPONENT = exports.DEFAULT_HSV_HUE_COMPONENT = exports.MAX_HSV_HUE_COMPONENT = exports.MIN_HSV_HUE_COMPONENT = void 0;
exports.MIN_HSV_HUE_COMPONENT = 0;
exports.MAX_HSV_HUE_COMPONENT = 360;
exports.DEFAULT_HSV_HUE_COMPONENT = exports.MIN_HSV_HUE_COMPONENT;
exports.MIN_HSV_SATURATION_COMPONENT = 0;
exports.MAX_HSV_SATURATION_COMPONENT = 100;
exports.DEFAULT_HSV_SATURATION_COMPONENT = exports.MIN_HSV_SATURATION_COMPONENT;
exports.MIN_HSV_VALUE_COMPONENT = 0;
exports.MAX_HSV_VALUE_COMPONENT = 100;
exports.DEFAULT_HSV_VALUE_COMPONENT = exports.MIN_HSV_VALUE_COMPONENT;
exports.DEFAULT = {
    input: {
        h: exports.DEFAULT_HSV_HUE_COMPONENT,
        s: exports.DEFAULT_HSV_SATURATION_COMPONENT,
        v: exports.DEFAULT_HSV_VALUE_COMPONENT,
    },
    return: [
        exports.DEFAULT_HSV_HUE_COMPONENT,
        exports.DEFAULT_HSV_SATURATION_COMPONENT,
        exports.DEFAULT_HSV_VALUE_COMPONENT,
    ],
};
