import { RgbObj } from 'types';
import { HexStringToRgbObjDefault } from './types';
export declare const MIN_RGB_COMPONENT_VALUE = 0;
export declare const MAX_RGB_COMPONENT_VALUE = 255;
export declare const DEFAULT_RGB_COLOR_COMPONENT = 0;
export declare const DEFAULT_RGB_ALPHA_COMPONENT = 1;
export declare const DEFAULT_HEX_COMPONENT = 0;
export declare const DEFAULT_RGB_OBJ: Required<RgbObj>;
export declare const DEFAULT_HEX_STRING = "#000000";
export declare const DEFAULT: HexStringToRgbObjDefault;
