import { HsvObjToStringDefault } from './types';

export const MIN_HSV_HUE_COMPONENT = 0;
export const MAX_HSV_HUE_COMPONENT = 360;
export const DEFAULT_HSV_HUE_COMPONENT = MIN_HSV_HUE_COMPONENT;

export const MIN_HSV_SATURATION_COMPONENT = 0;
export const MAX_HSV_SATURATION_COMPONENT = 100;
export const DEFAULT_HSV_SATURATION_COMPONENT = MIN_HSV_SATURATION_COMPONENT;

export const MIN_HSV_VALUE_COMPONENT = 0;
export const MAX_HSV_VALUE_COMPONENT = 100;
export const DEFAULT_HSV_VALUE_COMPONENT = MIN_HSV_VALUE_COMPONENT;

export const DEFAULT: HsvObjToStringDefault = {
  input: {
    h: DEFAULT_HSV_HUE_COMPONENT,
    s: DEFAULT_HSV_SATURATION_COMPONENT,
    v: DEFAULT_HSV_VALUE_COMPONENT,
  },
  return: `hsv(${DEFAULT_HSV_HUE_COMPONENT}, ${DEFAULT_HSV_SATURATION_COMPONENT}%, ${DEFAULT_HSV_VALUE_COMPONENT}%)`,
};
