import { DEFAULT } from '../constants';
import { CaseElements } from './types';

const DEFAULT_EXPECTED_VALUE = DEFAULT.return;

export const validCases: CaseElements = [
  { id: 1, input: [0, 0, 0], expected: { h: 0, s: 0, v: 0 } },
  { id: 2, input: [1, 2, 3], expected: { h: 1, s: 2, v: 3 } },
  { id: 3, input: [100, 100, 100], expected: { h: 100, s: 100, v: 100 } },
  { id: 4, input: [360, 100, 100], expected: { h: 360, s: 100, v: 100 } },
  { id: 5, input: [360, 360, 360], expected: { h: 360, s: 100, v: 100 } },
  { id: 6, input: [1000, 1000, 1000], expected: { h: 360, s: 100, v: 100 } },
  { id: 7, input: [-10, -100, -1], expected: { h: 0, s: 0, v: 0 } },
  { id: 8, input: [50, -3, 4], expected: { h: 50, s: 0, v: 4 } },
  { id: 9, input: [-22, 99, '39'], expected: { h: 0, s: 99, v: 39 } },
  { id: 10, input: ['43', '64.9', 5.3], expected: { h: 43, s: 64, v: 5 } },
  { id: 11, input: ['+6', '-5', '-4'], expected: { h: 6, s: 0, v: 0 } },
  { id: 12, input: [220.999, 101.4, 4.0001], expected: { h: 220, s: 100, v: 4 } },
  { id: 13, input: ['two', 'some', true], expected: { h: 0, s: 0, v: 1 } },
  { id: 14, input: [true, true, false], expected: { h: 1, s: 1, v: 0 } },
  { id: 15, input: [true, true, true], expected: { h: 1, s: 1, v: 1 } },
  { id: 16, input: [() => 2, () => 55, () => 1005], expected: { h: 2, s: 55, v: 100 } },
  { id: 17, input: [() => '+6', () => '-45', () => false], expected: { h: 6, s: 0, v: 0 } },
  { id: 18, input: [() => '--5', () => '++2', () => 0], expected: { h: 0, s: 0, v: 0 } },
  { id: 19, input: [() => 'some', () => 'five', () => true], expected: { h: 0, s: 0, v: 1 } },
  { id: 20, input: [() => 54, () => 54.3, () => 54.9], expected: { h: 54, s: 54, v: 54 } },
  { id: 21, input: () => [0, 0, 0], expected: { h: 0, s: 0, v: 0 } },
  { id: 22, input: () => [1, 2, 3], expected: { h: 1, s: 2, v: 3 } },
  { id: 23, input: () => [100, 100, 100], expected: { h: 100, s: 100, v: 100 } },
  { id: 24, input: () => [360, 100, 100], expected: { h: 360, s: 100, v: 100 } },
  { id: 25, input: () => [360, 360, 360], expected: { h: 360, s: 100, v: 100 } },
  { id: 26, input: () => [1000, 1000, 1000], expected: { h: 360, s: 100, v: 100 } },
  { id: 27, input: () => [-10, -100, -1], expected: { h: 0, s: 0, v: 0 } },
  { id: 28, input: () => [50, -3, 4], expected: { h: 50, s: 0, v: 4 } },
  { id: 29, input: () => [-22, 99, '39'], expected: { h: 0, s: 99, v: 39 } },
  { id: 30, input: () => ['43', '64.9', 5.3], expected: { h: 43, s: 64, v: 5 } },
  { id: 31, input: () => ['+6', '-5', '-4'], expected: { h: 6, s: 0, v: 0 } },
  { id: 32, input: () => [220.999, 101.4, 4.0001], expected: { h: 220, s: 100, v: 4 } },
  { id: 33, input: () => ['two', 'some', true], expected: { h: 0, s: 0, v: 1 } },
  { id: 34, input: () => [true, true, false], expected: { h: 1, s: 1, v: 0 } },
  { id: 35, input: () => [true, true, true], expected: { h: 1, s: 1, v: 1 } },
  { id: 36, input: () => [() => 2, () => 55, () => 1005], expected: { h: 2, s: 55, v: 100 } },
  { id: 37, input: () => [() => '+6', () => '-45', () => false], expected: { h: 6, s: 0, v: 0 } },
  { id: 38, input: () => [() => '--5', () => '++2', () => 0], expected: { h: 0, s: 0, v: 0 } },
  {
    id: 39,
    input: () => [() => 'some', () => 'five', () => true],
    expected: { h: 0, s: 0, v: 1 },
  },
  {
    id: 40,
    input: () => [() => 54, () => 54.3, () => 54.9],
    expected: { h: 54, s: 54, v: 54 },
  },
];

export const invalidCases: CaseElements = [
  { id: 1, input: 0, expected: DEFAULT_EXPECTED_VALUE },
  { id: 2, input: 44, expected: DEFAULT_EXPECTED_VALUE },
  { id: 3, input: '+89', expected: DEFAULT_EXPECTED_VALUE },
  { id: 4, input: 500, expected: DEFAULT_EXPECTED_VALUE },
  { id: 5, input: -1000, expected: DEFAULT_EXPECTED_VALUE },
  { id: 6, input: '-34', expected: DEFAULT_EXPECTED_VALUE },
  { id: 7, input: false, expected: DEFAULT_EXPECTED_VALUE },
  { id: 8, input: true, expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 9,
    input: { name: 'John' },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 10, input: 'John', expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 11,
    input: 3.3333,
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 12, input: () => 3, expected: DEFAULT_EXPECTED_VALUE },
  { id: 13, input: new Set(), expected: DEFAULT_EXPECTED_VALUE },
  { id: 14, input: new Map(), expected: DEFAULT_EXPECTED_VALUE },
  { id: 15, input: Symbol(4), expected: DEFAULT_EXPECTED_VALUE },
  { id: 16, input: new Error(), expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 17,
    input: { r: 'John', g: '++5', b: '--10' },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 18,
    input: { r: () => 'John', g: () => ({}), b: () => {} },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 19,
    input: { r: { name: 'John' }, g: {}, b: [] },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 20,
    input: { r: [34, 24, 'Aug', () => {}], g: [[], [2]], b: [[]] },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 21,
    input: { r: undefined, g: null, b: NaN },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 22,
    input: { r: () => undefined, g: () => null, b: () => NaN },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 23,
    input: { r: new Map(), g: new Set(), b: new Error() },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 24,
    input: { r: 'one', g: 'два', b: 'tri' },
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 25, input: () => 0, expected: DEFAULT_EXPECTED_VALUE },
  { id: 26, input: () => 44, expected: DEFAULT_EXPECTED_VALUE },
  { id: 27, input: () => '+89', expected: DEFAULT_EXPECTED_VALUE },
  { id: 28, input: () => 500, expected: DEFAULT_EXPECTED_VALUE },
  { id: 29, input: () => -1000, expected: DEFAULT_EXPECTED_VALUE },
  { id: 30, input: () => '-34', expected: DEFAULT_EXPECTED_VALUE },
  { id: 31, input: () => false, expected: DEFAULT_EXPECTED_VALUE },
  { id: 32, input: () => true, expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 33,
    input: () => ({ name: 'John' }),
    expected: DEFAULT_EXPECTED_VALUE,
  },
  { id: 34, input: () => 'John', expected: DEFAULT_EXPECTED_VALUE },
  {
    id: 35,
    input: null,
    expected: DEFAULT_EXPECTED_VALUE,
  },
  {
    id: 36,
    input: () => null,
    expected: DEFAULT_EXPECTED_VALUE,
  },
];
