import { RgbaObj } from 'types';
import { RgbObjToCmykObjDefault } from './types';
export declare const MIN_CMYK_COMPONENT_VALUE = 0;
export declare const MAX_CMYK_COMPONENT_VALUE = 100;
export declare const DEFAULT_CMYK_COLOR_COMPONENT = 0;
export declare const DEFAULT_CMYK_KEY_COMPONENT = 100;
export declare const MIN_RGB_COMPONENT_VALUE = 0;
export declare const MAX_RGB_COMPONENT_VALUE = 255;
export declare const DEFAULT_RGB_COLOR_COMPONENT = 0;
export declare const DEFAULT_RGB_ALPHA_COMPONENT = 1;
export declare const DEFAULT_RGB_OBJ: Required<RgbaObj>;
export declare const DEFAULT: RgbObjToCmykObjDefault;
