import { CaseElements } from './types';

export const validCases: CaseElements = [
  { id: 1, input: 0, expected: true },
  { id: 2, input: 1, expected: true },
  { id: 3, input: 22, expected: true },
  { id: 4, input: 3.3, expected: true },
  { id: 5, input: 102.222, expected: true },
  { id: 6, input: -10, expected: true },
  { id: 7, input: -0, expected: true },
  { id: 8, input: -52.25, expected: true },
  { id: 9, input: '0', expected: false },
  { id: 10, input: '1', expected: false },
  { id: 11, input: '22', expected: false },
  { id: 12, input: '3.3', expected: false },
  { id: 13, input: '102.222', expected: false },
  { id: 14, input: '-10', expected: false },
  { id: 15, input: '-0', expected: false },
  { id: 16, input: '-52.25', expected: false },
  { id: 17, input: () => '0', expected: false },
  { id: 18, input: () => 0, expected: false },
  { id: 19, input: () => 2, expected: false },
  { id: 20, input: () => -25, expected: false },
  { id: 21, input: () => 86.3, expected: false },
  { id: 22, input: false, expected: false },
  { id: 23, input: true, expected: false },
  { id: 24, input: Infinity, expected: false },
  { id: 25, input: -Infinity, expected: false },
  { id: 26, input: NaN, expected: false },
  { id: 27, input: null, expected: false },
  { id: 28, input: undefined, expected: false },
  { id: 29, input: [0, 1, 2], expected: false },
  { id: 30, input: [1, '5'], expected: false },
  { id: 31, input: new Set(), expected: false },
  { id: 32, input: new Map(), expected: false },
  { id: 33, input: new Array(1), expected: false },
  { id: 34, input: new Date(), expected: false },
  { id: 35, input: 'some', expected: false },
  { id: 36, input: 'one', expected: false },
  { id: 37, input: {}, expected: false },
  { id: 38, input: { value: 1 }, expected: false },
  { id: 39, input: { key: 1, name: 'Alina' }, expected: false },
  { id: 40, input: Symbol(4), expected: false },
  { id: 41, input: Symbol('text'), expected: false },
];
