"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT = exports.DEFAULT_RGB_OBJ = exports.DEFAULT_RGB_ALPHA_COMPONENT = exports.DEFAULT_RGB_COLOR_COMPONENT = exports.MAX_RGB_COMPONENT_VALUE = exports.MIN_RGB_COMPONENT_VALUE = exports.DEFAULT_HSV_VALUE_COMPONENT = exports.MAX_HSV_VALUE_COMPONENT = exports.MIN_HSV_VALUE_COMPONENT = exports.DEFAULT_HSV_SATURATION_COMPONENT = exports.MAX_HSV_SATURATION_COMPONENT = exports.MIN_HSV_SATURATION_COMPONENT = exports.DEFAULT_HSV_HUE_COMPONENT = exports.MAX_HSV_HUE_COMPONENT = exports.MIN_HSV_HUE_COMPONENT = void 0;
exports.MIN_HSV_HUE_COMPONENT = 0;
exports.MAX_HSV_HUE_COMPONENT = 360;
exports.DEFAULT_HSV_HUE_COMPONENT = exports.MIN_HSV_HUE_COMPONENT;
exports.MIN_HSV_SATURATION_COMPONENT = 0;
exports.MAX_HSV_SATURATION_COMPONENT = 100;
exports.DEFAULT_HSV_SATURATION_COMPONENT = exports.MIN_HSV_SATURATION_COMPONENT;
exports.MIN_HSV_VALUE_COMPONENT = 0;
exports.MAX_HSV_VALUE_COMPONENT = 100;
exports.DEFAULT_HSV_VALUE_COMPONENT = exports.MIN_HSV_VALUE_COMPONENT;
exports.MIN_RGB_COMPONENT_VALUE = 0;
exports.MAX_RGB_COMPONENT_VALUE = 255;
exports.DEFAULT_RGB_COLOR_COMPONENT = exports.MIN_RGB_COMPONENT_VALUE;
exports.DEFAULT_RGB_ALPHA_COMPONENT = 1;
exports.DEFAULT_RGB_OBJ = {
    r: exports.DEFAULT_RGB_COLOR_COMPONENT,
    g: exports.DEFAULT_RGB_COLOR_COMPONENT,
    b: exports.DEFAULT_RGB_COLOR_COMPONENT,
    a: exports.DEFAULT_RGB_ALPHA_COMPONENT,
};
exports.DEFAULT = {
    input: exports.DEFAULT_RGB_OBJ,
    return: {
        h: exports.DEFAULT_HSV_HUE_COMPONENT,
        s: exports.DEFAULT_HSV_SATURATION_COMPONENT,
        v: exports.DEFAULT_HSV_VALUE_COMPONENT,
    },
};
