import { HsvArrayToObjDefault } from './types';
export declare const MIN_HSV_HUE_COMPONENT = 0;
export declare const MAX_HSV_HUE_COMPONENT = 360;
export declare const DEFAULT_HSV_HUE_COMPONENT = 0;
export declare const MIN_HSV_SATURATION_COMPONENT = 0;
export declare const MAX_HSV_SATURATION_COMPONENT = 100;
export declare const DEFAULT_HSV_SATURATION_COMPONENT = 0;
export declare const MIN_HSV_VALUE_COMPONENT = 0;
export declare const MAX_HSV_VALUE_COMPONENT = 100;
export declare const DEFAULT_HSV_VALUE_COMPONENT = 0;
export declare const DEFAULT: HsvArrayToObjDefault;
