import { HsvObj } from '../../../../types';
import { HsvObjToRgbObjDefault } from './types';

export const MIN_HSV_HUE_COMPONENT = 0;
export const MAX_HSV_HUE_COMPONENT = 360;
export const DEFAULT_HSV_HUE_COMPONENT = MIN_HSV_HUE_COMPONENT;

export const MIN_HSV_SATURATION_COMPONENT = 0;
export const MAX_HSV_SATURATION_COMPONENT = 100;
export const DEFAULT_HSV_SATURATION_COMPONENT = MIN_HSV_SATURATION_COMPONENT;

export const MIN_HSV_VALUE_COMPONENT = 0;
export const MAX_HSV_VALUE_COMPONENT = 100;
export const DEFAULT_HSV_VALUE_COMPONENT = MIN_HSV_VALUE_COMPONENT;

export const MIN_RGB_COMPONENT_VALUE = 0;
export const MAX_RGB_COMPONENT_VALUE = 255;
export const DEFAULT_RGB_COLOR_COMPONENT = MIN_RGB_COMPONENT_VALUE;
export const DEFAULT_RGB_ALPHA_COMPONENT = 1;

export const DEFAULT_HSV_OBJ: Required<HsvObj> = {
  h: DEFAULT_HSV_HUE_COMPONENT,
  s: DEFAULT_HSV_SATURATION_COMPONENT,
  v: DEFAULT_HSV_VALUE_COMPONENT,
};

export const DEFAULT: HsvObjToRgbObjDefault = {
  input: DEFAULT_HSV_OBJ,
  return: {
    r: DEFAULT_RGB_COLOR_COMPONENT,
    g: DEFAULT_RGB_COLOR_COMPONENT,
    b: DEFAULT_RGB_COLOR_COMPONENT,
    a: DEFAULT_RGB_ALPHA_COMPONENT,
  },
};
