#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/../config/branch-config.sh"

branch_name=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch_name" = "docs" ]; then
  exit 0
fi

wrong_name_msg="Error: '$branch_name' branch name does not match the installed format.\nThe branch name should start with one of the following prefixes: $VALID_PREFIXES."

if [[ ! "$branch_name" =~ ^($VALID_PREFIXES)/.+ ]]; then
  echo "$wrong_name_msg"
  exit 1
fi
