#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git rev-parse --abbrev-ref HEAD)

if [[ $branch_name == chore* || $branch_name == docs* ]]; then
  exit 0
fi

npm install

npm run build

npm test
