import { CaseElements } from './types';

export const validCases: CaseElements = [
  { id: 1, input: 0, expected: false },
  { id: 2, input: 55, expected: false },
  { id: 3, input: -50, expected: false },
  { id: 4, input: 185.4, expected: false },
  { id: 5, input: -5435.66, expected: false },
  { id: 6, input: '', expected: true },
  { id: 7, input: '0', expected: false },
  { id: 8, input: '454', expected: false },
  { id: 9, input: 'text', expected: false },
  { id: 10, input: '-4', expected: false },
  { id: 11, input: 'some value', expected: false },
  { id: 12, input: [], expected: true },
  { id: 13, input: [1], expected: false },
  { id: 14, input: [0], expected: false },
  { id: 15, input: [-2], expected: false },
  { id: 16, input: [1, 2, 3], expected: false },
  { id: 17, input: [-1, -2, 3, 'text', false], expected: false },
  { id: 18, input: false, expected: false },
  { id: 19, input: true, expected: false },
  { id: 20, input: null, expected: true },
  { id: 21, input: undefined, expected: true },
  { id: 22, input: -Infinity, expected: false },
  { id: 23, input: Infinity, expected: false },
  { id: 24, input: NaN, expected: false },
  { id: 25, input: {}, expected: true },
  { id: 26, input: { name: 'Alina' }, expected: false },
  { id: 27, input: { value: null }, expected: false },
  { id: 28, input: { a: 1, b: 2, c: 3 }, expected: false },
  { id: 29, input: () => {}, expected: false },
  { id: 30, input: () => undefined, expected: false },
  { id: 31, input: () => null, expected: false },
  { id: 32, input: () => [], expected: false },
  { id: 33, input: new Date(), expected: false },
  { id: 34, input: new Date('2025-01-02'), expected: false },
  { id: 35, input: new Set(), expected: true },
  { id: 36, input: new Map(), expected: true },
  { id: 37, input: new Set(['f', false, 0]), expected: false },
  { id: 38, input: new Set([undefined]), expected: false },
  { id: 39, input: new Map([['key1', 'value1']]), expected: false },
  {
    id: 40,
    input: new Map([
      ['key1', 'value1'],
      ['key2', 'value2'],
    ]),
    expected: false,
  },
  { id: 41, input: Symbol('text'), expected: false },
  { id: 42, input: Symbol(23), expected: false },
  { id: 43, input: Symbol(undefined), expected: false },
  { id: 44, input: Symbol(0), expected: false },
];
